### ISSUE TITLE
使用的reckit版本可能比较旧了，在 Python 3.10中，'Iterable`类型已经从`collections`模块中移除，而应该从'collections.abc`模块中导入。

### ISSUE THREAD

**Issue by Konisberg** [LehengTHU/Agent4Rec#2]
省流：

建议自行修改 "myvenv/lib/python3.10/site-packages/reckit/util/decorators.py"

删除
from collections import Iterable

增加
from collections.abc import Iterable

别的没了，整体代码都比较清楚，一目了然，就不多赘述了。
以及如果有时间的话，建议把reckit直接换掉，因为reckit从202006开始到202011，然后就没有再维护过了，以后还可以出现更多的问题（当然，发完paper以后没什么时间维护，当我没说（手动狗头

**Comment by Konisberg** [comment]
懒得pr了，就这样吧

**Comment by Konisberg** [comment]
懒得pr了，就这样吧……

祝大家paper++

**Comment by Konisberg** [comment]
btw，最初安装的时候，建议先把reckit==0.2.4删掉，使用`pip install -r requirements.txt`安装完其他pkg，再安装这个

**Comment by LehengTHU** [comment]
感谢提醒~我最近会再更新一版repo的readme，把你说的问题记录下来，非常感谢！

**Comment by Konisberg** [comment]
> 感谢提醒~我最近会再更新一版repo的readme，把你说的问题记录下来，非常感谢！

我稍早些时候搜索了一下，发现reckit似乎确实已经无人维护（Unmaintained）了，建议有时间的话换一个stable一点的pkg

（当然，我在reckit发布之前就不做recsys了）

upgrade就得靠 @LehengTHU 了，我只是抛砖引玉啦：）
