### ISSUE TITLE
About figure 13 in the paper

### ISSUE THREAD

**Issue by HuangFuSL** [LehengTHU/Agent4Rec#3]
Sorry for the interruption. According to $S_{act}^u$ provided in appendix C.2. It seems that since $\hat y_{i}\in \{0, 1\}$, $S_{act}^u$ should be an integer. However, in Figure 13 (b), some agents corresponds to a non-integral $S_{act}^u$ (see the red lines in the picture, the lines may not be precise but sufficient to show the problem). Could you please provide some explanation on it?

<img width="902" alt="Screenshot 2024-05-09 at 14 05 21" src="https://github.com/LehengTHU/Agent4Rec/assets/56627153/39f59fd0-c15d-4005-aaef-d817e4c15a1e">

**Comment by LehengTHU** [comment]
Thanks for your question. Actually, we adopted a rolling average strategy on the x-axis to make this figure more smooth. Sorry for this confusion.

**Comment by LehengTHU** [comment]
Thanks for your question. Actually, we adopted a rolling average strategy on the x-axis to avoid the effects of some noisy agent behaviors, which also leads to the non-integer in this figure. Sorry for this confusion.

**Comment by HuangFuSL** [comment]
I see, and thanks for your reply.
